if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
    set(CLUEAPI_IS_TOP_LEVEL TRUE)
else()
    set(CLUEAPI_IS_TOP_LEVEL FALSE)
endif()

if(CLUEAPI_IS_TOP_LEVEL OR NOT DEFINED CMAKE_CXX_STANDARD)
    set(CMAKE_CXX_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
endif()

if(NOT TARGET Boost::system)
    set(Boost_USE_STATIC_LIBS ON)

    if(WIN32)
        set(Boost_USE_STATIC_RUNTIME ON)
    endif()
endif()

if(NOT DEFINED CLUEAPI_USE_NLOHMANN_JSON)
    option(CLUEAPI_USE_NLOHMANN_JSON "Enable nlohmann/json support" ON)
endif()

if(NOT DEFINED CLUEAPI_USE_CUSTOM_JSON)
    option(CLUEAPI_USE_CUSTOM_JSON "Enable custom json support" OFF)
endif()

if(NOT DEFINED CLUEAPI_USE_LOGGING_MODULE)
    option(CLUEAPI_USE_LOGGING_MODULE "Enable logging module support" ON)
endif()

if(NOT DEFINED CLUEAPI_USE_DOTENV_MODULE)
    option(CLUEAPI_USE_DOTENV_MODULE "Enable dotenv module support" ON)
endif()

if(NOT DEFINED CLUEAPI_USE_REDIS_MODULE)
    option(CLUEAPI_USE_REDIS_MODULE "Enable redis module support" ON)
endif()

if(NOT DEFINED CLUEAPI_BUILD_TESTS)
    option(CLUEAPI_BUILD_TESTS "Build tests" OFF)
endif()

if(NOT DEFINED CLUEAPI_OPTIMIZED_LOG_LEVEL)
    set(CLUEAPI_OPTIMIZED_LOG_LEVEL INFO CACHE STRING "Optimized log level")
endif()

set_property(CACHE CLUEAPI_OPTIMIZED_LOG_LEVEL PROPERTY STRINGS TRACE DEBUG INFO WARNING ERROR CRITICAL NONE)

set(LOG_LEVELS "TRACE;DEBUG;INFO;WARNING;ERROR;CRITICAL;NONE")

list(FIND LOG_LEVELS ${CLUEAPI_OPTIMIZED_LOG_LEVEL} CLUEAPI_LOG_LEVEL_NUM)

if(CLUEAPI_LOG_LEVEL_NUM EQUAL -1)
    set(CLUEAPI_LOG_LEVEL_NUM 2)

    if(CLUEAPI_IS_TOP_LEVEL)
        message(WARNING "Unknown log level: ${CLUEAPI_OPTIMIZED_LOG_LEVEL}, defaulting to INFO (2)")
    endif()
endif()

if(CLUEAPI_USE_CUSTOM_JSON)
    set(CLUEAPI_USE_NLOHMANN_JSON OFF)
endif()

if(WIN32)
    add_compile_definitions(_WIN32_WINNT=0x0A00)
endif()

message(STATUS "CLUEAPI configuration summary:")
message(STATUS "  CLUEAPI_USE_NLOHMANN_JSON = ${CLUEAPI_USE_NLOHMANN_JSON}")
message(STATUS "  CLUEAPI_USE_CUSTOM_JSON = ${CLUEAPI_USE_CUSTOM_JSON}")
message(STATUS "  CLUEAPI_USE_LOGGING_MODULE = ${CLUEAPI_USE_LOGGING_MODULE}")
message(STATUS "  CLUEAPI_USE_DOTENV_MODULE = ${CLUEAPI_USE_DOTENV_MODULE}")
message(STATUS "  CLUEAPI_USE_REDIS_MODULE = ${CLUEAPI_USE_REDIS_MODULE}")
message(STATUS "  CLUEAPI_BUILD_TESTS = ${CLUEAPI_BUILD_TESTS}")
message(STATUS "  CLUEAPI_OPTIMIZED_LOG_LEVEL = ${CLUEAPI_OPTIMIZED_LOG_LEVEL} (${CLUEAPI_LOG_LEVEL_NUM})")